spring.application.name=algovault

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/algovault
spring.datasource.username=postgres
spring.datasource.password=Gzna25i1i2
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379